"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import jsPDF from "jspdf";
import { GoogleGenerativeAI } from "@google/generative-ai";

const ai = new GoogleGenerativeAI("AIzaSyDkpJZnCkaE1PR_beRM3WSXdx8eGQs5T38");

import {
    Upload,
    ImageIcon,
    Loader2,
    Leaf,
    Pill,
    Store,
    BarChart3,
} from "lucide-react";
import BackButton from "../components/ui/BackButton";


export default function ScanPage() {
    const [image, setImage] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [file, setFile] = useState<File | null>(null);
    const [solution, setSolution] = useState<string | null>(null);
    const [loadingGemini, setLoadingGemini] = useState(false);


    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const selectedFile = e.target.files?.[0];

        if (selectedFile) {
            setFile(selectedFile);   // ✅ IMPORTANT
            setImage(URL.createObjectURL(selectedFile));
            setResult(null);
        }
    };

    const getGeminiSolution = async (disease: string) => {
        try {
            const model = ai.getGenerativeModel({ model: "gemini-pro" });

            const response = await model.generateContent({
                contents: [{
                    role: "user",
                    parts: [{
                        text: `suggest the Best medicine for this crop disease: ${disease}. also give 3 points of DOs and 3 points of DON'Ts for farmers. Finally, give the name of the medicine clearly in a section called 'MEDICINE'.`
                    }]
                }],
                generationConfig: {
                    maxOutputTokens: 500,
                }
            });

            const result = await response.response;
            const text = result.text();

            return text || "No suggestions available";
        } catch (err) {
            console.error("Gemini Error:", err);
            return "Failed to get AI suggestions";
        }
    };

    const generatePDF = () => {
        if (!result) return;

        const doc = new jsPDF();

        doc.setFontSize(22);
        doc.setTextColor(34, 197, 94);
        doc.text("AgroVision AI - Diagnosis Report", 20, 20);

        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text(`Disease: ${result.disease}`, 20, 40);
        doc.text(`Confidence: ${result.confidence}`, 20, 50);
        doc.text(`Medicine: ${result.medicine}`, 20, 60);
        doc.text(`Nearby Shop: ${result.shop}`, 20, 70);

        doc.text("Thank you for using AgroVision AI.", 20, 90);

        doc.setFontSize(12);

        doc.text("Important Advisory:", 20, 110);

        doc.text(
            "Early detection and timely treatment of crop diseases are essential",
            20,
            120
        );
        doc.text(
            "to prevent major crop damage and infection spread across fields.",
            20,
            130
        );
        doc.text(
            "Proper use of recommended medicines protects crop quality and yield.",
            20,
            140
        );
        doc.text(
            "Regular monitoring reduces long-term financial losses.",
            20,
            150
        );
        doc.text(
            "AgroVision AI recommends immediate action based on this report.",
            20,
            160
        );


        doc.text(`Generated On: ${new Date().toLocaleString()}`, 20, 190);
        doc.text("Report Generated By AgroVision AI", 20, 180);
        doc.save("AgroVision_AI_Report.pdf");
    };


    const handleBuyMedicine = () => {
        if (!result?.medicine) return;

        const query = encodeURIComponent(result.medicine);
        const flipkartURL = `https://www.flipkart.com/search?q=${query}`;

        window.open(flipkartURL, "_blank");
    };

    const handleWatchVideo = () => {
        if (!result?.disease) return;

        const query = encodeURIComponent(result.disease + " treatment");

        const youtubeURL = `https://www.youtube.com/results?search_query=${query}`;

        window.open(youtubeURL, "_blank");
    };

    const handleAnalyze = async () => {
        if (!file) {
            alert("Please upload image");
            return;
        }

        setLoading(true);
        setResult(null);
        setSolution(null); // reset

        try {
            const formData = new FormData();
            formData.append("file", file);

            const res = await fetch("http://127.0.0.1:8000/predict", {
                method: "POST",
                body: formData,
            });

            const data = await res.json();

            console.log("API 👉", data);

            const cleanName = data.class
                .replace("___", " - ")
                .replace(/_/g, " ");

            setResult({
                disease: cleanName,
                confidence: data.confidence + " %",
                medicine: "Coming soon",
                shop: "Coming soon",
            });

            // 🔥 Gemini call AFTER result
            setLoadingGemini(true);

            getGeminiSolution(cleanName).then((res) => {
                setSolution(res);
                setLoadingGemini(false);
            });

        } catch (err: any) {
            console.error("Fetch Error:", err);
            if (err.name === 'TypeError' && err.message === 'Failed to fetch') {
                alert("Backend server error: Please make sure your Python/FastAPI server is running at http://127.0.0.1:8000");
            } else {
                alert("An unexpected error occurred during analysis: " + err.message);
            }
        }

        setLoading(false);
    };
    const extractMedicine = (text: string) => {
        const match = text.match(/Name:\s*(.*)/i);
        return match ? match[1] : "Recommended Medicine";
    };
    const getBuyLink = (medicine: string) => {
        const query = encodeURIComponent(medicine);
        return `https://www.flipkart.com/search?q=${query}`;
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-green-50 to-white dark:from-[#0f1f14] dark:to-[#0b1510] px-6 md:px-20 py-20 transition-colors">
            <div className="max-w-6xl mx-auto">
                <BackButton />

                {/* Header */}
                <motion.div
                    initial={{ opacity: 0, y: -40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="text-center mb-16"
                >
                    <h1 className="text-5xl font-bold text-green-700 dark:text-green-400 flex justify-center items-center gap-4">
                        <Leaf size={40} /> Scan Your Crop
                    </h1>
                    <p className="mt-4 text-gray-600 dark:text-gray-300 text-lg">
                        Upload a leaf image and let AgroVision AI detect diseases instantly.
                    </p>
                </motion.div>

                {/* Upload Section */}
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="max-w-3xl mx-auto bg-[#DBFCE7] dark:bg-[#13281b] p-10 rounded-2xl shadow-xl border border-green-200 dark:border-green-800"
                >
                    {!image ? (
                        <label className="flex flex-col items-center justify-center border-2 border-dashed border-green-400 rounded-xl p-10 cursor-pointer hover:bg-green-50 dark:hover:bg-green-900 transition">
                            <Upload size={40} className="text-green-600 dark:text-green-400" />
                            <p className="mt-4 text-green-700 dark:text-green-300">
                                Click to Upload Leaf Image
                            </p>
                            <input
                                type="file"
                                accept="image/*"
                                className="hidden"
                                onChange={handleImageUpload}
                            />
                        </label>
                    ) : (
                        <div className="text-center">
                            <motion.img
                                initial={{ opacity: 0, scale: 0.8 }}
                                animate={{ opacity: 1, scale: 1 }}
                                src={image}
                                alt="Selected Crop"
                                className="w-full max-h-80 object-cover rounded-xl shadow-lg mb-6"
                            />
                            <div className="flex gap-4 justify-center">
                                <button
                                    onClick={() => setImage(null)}
                                    className="px-6 py-2 bg-red-500 text-white rounded-lg font-bold hover:bg-red-600 transition"
                                >
                                    Remove
                                </button>
                                <button
                                    onClick={handleAnalyze}
                                    disabled={loading}
                                    className="px-8 py-2 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 flex items-center gap-2 transition"
                                >
                                    {loading ? <Loader2 className="animate-spin" /> : "Analyze Now"}
                                </button>
                            </div>
                        </div>
                    )}
                </motion.div>

                {/* Results Section */}
                {result && (
                    <motion.div
                        initial={{ opacity: 0, scale: 0.9 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="mt-12 grid grid-cols-1 md:grid-cols-2 gap-8"
                    >
                        <div className="bg-white dark:bg-[#13281b] p-8 rounded-2xl shadow-lg border border-green-200 dark:border-green-800">
                            <h2 className="text-2xl font-bold text-green-700 dark:text-green-400 mb-6 flex items-center gap-2">
                                <BarChart3 size={24} /> Analysis Result
                            </h2>
                            <div className="space-y-4">
                                <p className="text-lg dark:text-gray-200">
                                    <span className="font-bold text-green-600">Disease:</span> {result.disease}
                                </p>
                                <p className="text-lg dark:text-gray-200">
                                    <span className="font-bold text-green-600">Confidence:</span> {result.confidence}
                                </p>
                                <div className="flex gap-4 mt-8">
                                    <button
                                        onClick={generatePDF}
                                        className="flex-1 py-3 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 transition"
                                    >
                                        Download Report
                                    </button>
                                    <button
                                        onClick={handleWatchVideo}
                                        className="flex-1 py-3 border-2 border-green-600 text-green-600 rounded-lg font-bold hover:bg-green-600 hover:text-white transition"
                                    >
                                        Watch Video
                                    </button>
                                </div>
                            </div>
                        </div>

                        {/* Gemini Solution Section */}
                        <div className="bg-white dark:bg-[#13281b] p-8 rounded-2xl shadow-lg border border-green-200 dark:border-green-800">
                            <h2 className="text-2xl font-bold text-green-700 dark:text-green-400 mb-6 flex items-center gap-2">
                                <Pill size={24} /> AI Suggestions
                            </h2>
                            {loadingGemini ? (
                                <div className="flex flex-col items-center justify-center py-10">
                                    <Loader2 size={32} className="animate-spin text-green-500 mb-4" />
                                    <p className="text-gray-500 dark:text-gray-400">Consulting AgroVision AI...</p>
                                </div>
                            ) : (
                                <div className="prose dark:prose-invert max-w-none">
                                    <div className="whitespace-pre-wrap text-gray-700 dark:text-gray-300 leading-relaxed">
                                        {solution}
                                    </div>
                                    {solution && (
                                        <motion.div
                                            initial={{ opacity: 0 }}
                                            animate={{ opacity: 1 }}
                                            className="mt-8 p-4 bg-green-50 dark:bg-green-900/20 rounded-xl border border-green-200 dark:border-green-800 flex justify-between items-center"
                                        >
                                            <div>
                                                <p className="text-xs text-green-600 font-bold uppercase tracking-wider">Recommended Medicine</p>
                                                <p className="text-lg font-bold text-green-800 dark:text-green-200">{extractMedicine(solution)}</p>
                                            </div>
                                            <a
                                                href={getBuyLink(extractMedicine(solution))}
                                                target="_blank"
                                                className="px-6 py-2 bg-green-600 text-white rounded-lg font-bold hover:bg-green-700 transition flex items-center gap-2"
                                            >
                                                <Store size={18} /> Buy Now
                                            </a>
                                        </motion.div>
                                    )}
                                </div>
                            )}
                        </div>
                    </motion.div>
                )}
            </div>
        </div>
    );
}
