"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import jsPDF from "jspdf";

import {
    Upload,
    ImageIcon,
    Loader2,
    Leaf,
    Pill,
    Store,
    BarChart3,
} from "lucide-react";

export default function ScanPage() {
    const [image, setImage] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<any>(null);

    const handleImageUpload = (e: any) => {
        const file = e.target.files[0];
        if (file) {
            setImage(URL.createObjectURL(file));
            setResult(null);
        }
    };

    const handleDownloadPDF = () => {
        if (!result) return;

        const doc = new jsPDF();

        doc.setFontSize(18);
        doc.text("AgroVision AI - Crop Disease Report", 20, 20);

        doc.setFontSize(14);
        doc.text(`Disease: ${result.disease}`, 20, 40);
        doc.text(`Confidence: ${result.confidence}`, 20, 50);
        doc.text(`Medicine: ${result.medicine}`, 20, 60);
        doc.text(`Nearby Shop: ${result.shop}`, 20, 70);

        doc.text("Thank you for using AgroVision AI.", 20, 90);

        doc.setFontSize(12);

        doc.text("Important Advisory:", 20, 110);

        doc.text(
            "Early detection and timely treatment of crop diseases are essential",
            20,
            120
        );
        doc.text(
            "to prevent major crop damage and infection spread across fields.",
            20,
            130
        );
        doc.text(
            "Proper use of recommended medicines protects crop quality and yield.",
            20,
            140
        );
        doc.text(
            "Regular monitoring reduces long-term financial losses.",
            20,
            150
        );
        doc.text(
            "AgroVision AI recommends immediate action based on this report.",
            20,
            160
        );


        doc.text(`Generated On: ${new Date().toLocaleString()}`, 20, 190);
        doc.text("Report Generated By AgroVision AI", 20, 180);
        doc.save("AgroVision_AI_Report.pdf");
    };
    const handleBuyMedicine = () => {
        if (!result?.medicine) return;

        const query = encodeURIComponent(result.medicine);
        const flipkartURL = `https://www.flipkart.com/search?q=${query}`;

        window.open(flipkartURL, "_blank");
    };


    const dummyResults = [
        {
            disease: "Leaf Rust",
            confidence: "92%",
            medicine: "Mancozeb Fungicide",
            shop: "Krishi Agro Center - 2km away",
        },
        {
            disease: "Powdery Mildew",
            confidence: "88%",
            medicine: "Sulfur Fungicide Spray",
            shop: "GreenField Agro Store - 1.5km away",
        },
        {
            disease: "Bacterial Blight",
            confidence: "90%",
            medicine: "Copper Oxychloride",
            shop: "FarmCare Supplies - 3km away",
        },
        {
            disease: "Early Leaf Spot",
            confidence: "85%",
            medicine: "Chlorothalonil Spray",
            shop: "Agro Mart - 2.8km away",
        },
        {
            disease: "Downy Mildew",
            confidence: "93%",
            medicine: "Metalaxyl Fungicide",
            shop: "Kisan Agro Point - 1km away",
        },
    ];

    const handleWatchVideo = () => {
        if (!result?.disease) return;

        const query = encodeURIComponent(
            `${result.disease} plant disease treatment`
        );

        const youtubeURL = `https://www.youtube.com/results?search_query=${query}`;

        window.open(youtubeURL, "_blank");
    };


    const handleAnalyze = async () => {
        setLoading(true);

        setTimeout(() => {
            const randomIndex = Math.floor(Math.random() * dummyResults.length);
            setResult(dummyResults[randomIndex]);
            setLoading(false);
        }, 2500);
    };


    return (
        <div className="min-h-screen bg-gradient-to-br from-green-50 to-white dark:from-[#0f1f14] dark:to-[#0b1510] px-6 md:px-20 py-20 transition-colors">

            {/* Header */}
            <motion.div
                initial={{ opacity: 0, y: -40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="text-center mb-16"
            >
                <h1 className="text-5xl font-bold text-green-700 dark:text-green-400 flex justify-center items-center gap-4">
                    <Leaf size={40} /> Scan Your Crop
                </h1>
                <p className="mt-4 text-gray-600 dark:text-gray-300 text-lg">
                    Upload a leaf image and let AgroVision AI detect diseases instantly.
                </p>
            </motion.div>

            {/* Upload Section */}
            <motion.div
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="max-w-3xl mx-auto bg-[#DBFCE7] dark:bg-[#13281b] p-10 rounded-2xl shadow-xl border border-green-200 dark:border-green-800"
            >
                {!image ? (
                    <label className="flex flex-col items-center justify-center border-2 border-dashed border-green-400 rounded-xl p-10 cursor-pointer hover:bg-green-50 dark:hover:bg-green-900 transition">
                        <Upload size={40} className="text-green-600 dark:text-green-400" />
                        <p className="mt-4 text-green-700 dark:text-green-300">
                            Click to Upload Leaf Image
                        </p>
                        <input
                            type="file"
                            accept="image/*"
                            className="hidden"
                            onChange={handleImageUpload}
                        />
                    </label>
                ) : (
                    <div className="text-center">
                        <img
                            src={image}
                            alt="preview"
                            className="mx-auto h-64 object-cover rounded-xl shadow-md"
                        />

                        <button
                            onClick={handleAnalyze}
                            className="mt-8 px-8 py-3 font-bold cursor-pointer bg-green-600 text-white rounded-xl hover:scale-105 transition flex items-center justify-center gap-3 mx-auto"
                        >
                            <ImageIcon size={20} /> Analyze Leaf
                        </button>
                    </div>
                )}
            </motion.div>

            {/* Loading Spinner */}
            {loading && (
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex justify-center mt-10"
                >
                    <Loader2 className="animate-spin text-green-600" size={40} />
                </motion.div>
            )}

            {/* Result Section */}
            {result && (
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="max-w-4xl mx-auto mt-16 bg-[#DBFCE7] dark:bg-[#13281b] p-10 rounded-2xl shadow-xl border border-green-200 dark:border-green-800"
                >
                    <h2 className="text-3xl text-green-700 dark:text-green-400 mb-8 text-center font-bold">
                        Scan Result
                    </h2>

                    <div className="grid md:grid-cols-2 gap-10">
                        <div className="space-y-6">
                            <div className="flex items-center gap-4">
                                <Leaf className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Disease:</strong> {result.disease}</p>
                            </div>

                            <div className="flex items-center gap-4">
                                <BarChart3 className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Confidence:</strong> {result.confidence}</p>
                            </div>

                            <div className="flex items-center gap-4">
                                <Pill className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Medicine:</strong> {result.medicine}</p>
                            </div>

                            <div className="flex items-center gap-4">
                                <Store className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Nearby Shop:</strong> {result.shop}</p>
                            </div>
                        </div>

                        <div className="bg-green-50 dark:bg-[#284131b9] p-6 rounded-xl">
                            <p className="font-semibold text-green-700 dark:text-green-300">
                                Recommended Action:
                            </p>
                            <p className="mt-3 text-gray-700 dark:text-gray-100">
                                Apply treatment immediately and monitor crop condition for the
                                next 5-7 days. Avoid overwatering and ensure proper sunlight.
                            </p>
                            <div className="flex justify-between gap-2">



                                <button onClick={handleBuyMedicine} className= " cursor-pointer mt-6 px-6 py-2 bg-green-700 text-white rounded-lg hover:scale-105 transition">
                                    Buy Medicine Online
                                </button>
                                <button
                                    onClick={handleWatchVideo}
                                    className="mt-6 px-6 py-2 bg-red-600 cursor-pointer text-white rounded-lg hover:scale-105 transition"
                                >
                                    Watch Video
                                </button>
                            </div>
                        </div>


                    </div>

                </motion.div>

            )}


            {
                result &&
                <div className="mx-auto w-fit">



                    <div className="mt-6 inline-block relative rounded-xl p-[2px] overflow-hidden">

                        {/* Rotating gradient border */}
                        <div className="absolute inset-0 bg-gradient-to-r from-emerald-400 via-yellow-400 to-green-500 animate-rotate rounded-xl dark:bg-yellow-300"></div>

                        {/* Actual button */}
                        <button
                            onClick={handleDownloadPDF}
                            className="relative px-6 cursor-pointer py-2 bg-[#0f1f14] text-white font-semibold rounded-xl hover:scale-105 transition duration-300 dark:bg-yellow-800"
                        >
                            Download PDF
                        </button>
                    </div>
                </div>
            }
        </div>
    );
}
