"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import jsPDF from "jspdf";
import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({
    apiKey: "AIzaSyDkpJZnCkaE1PR_beRM3WSXdx8eGQs5T38",
});

import {
    Upload,
    ImageIcon,
    Loader2,
    Leaf,
    Pill,
    Store,
    BarChart3,
} from "lucide-react";


export default function ScanPage() {
    const [image, setImage] = useState<string | null>(null);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState<any>(null);
    const [file, setFile] = useState<File | null>(null);
    const [solution, setSolution] = useState<string | null>(null);
    const [loadingGemini, setLoadingGemini] = useState(false);


    const handleImageUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
        const selectedFile = e.target.files?.[0];

        if (selectedFile) {
            setFile(selectedFile);   // ✅ IMPORTANT
            setImage(URL.createObjectURL(selectedFile));
            setResult(null);
        }
    };
    const handleDownloadPDF = () => {
        if (!result) return;

        const doc = new jsPDF();

        doc.setFontSize(18);
        doc.text("AgroVision AI - Crop Disease Report", 20, 20);

        doc.setFontSize(14);
        doc.text(`Disease: ${result.disease}`, 20, 40);
        doc.text(`Confidence: ${result.confidence}`, 20, 50);
        doc.text(`Medicine: ${result.medicine}`, 20, 60);
        doc.text(`Nearby Shop: ${result.shop}`, 20, 70);

        doc.text("Thank you for using AgroVision AI.", 20, 90);

        doc.setFontSize(12);

        doc.text("Important Advisory:", 20, 110);

        doc.text(
            "Early detection and timely treatment of crop diseases are essential",
            20,
            120
        );
        doc.text(
            "to prevent major crop damage and infection spread across fields.",
            20,
            130
        );
        doc.text(
            "Proper use of recommended medicines protects crop quality and yield.",
            20,
            140
        );
        doc.text(
            "Regular monitoring reduces long-term financial losses.",
            20,
            150
        );
        doc.text(
            "AgroVision AI recommends immediate action based on this report.",
            20,
            160
        );


        doc.text(`Generated On: ${new Date().toLocaleString()}`, 20, 190);
        doc.text("Report Generated By AgroVision AI", 20, 180);
        doc.save("AgroVision_AI_Report.pdf");
    };


    const getGeminiSolution = async (disease: string) => {
        try {
            const response = await ai.models.generateContent({
                model: "gemini-3-flash-preview", // ✅ latest working
                contents: `
Plant disease: ${disease}

Return ONLY plain text. No code, no explanation.

Format exactly like this:

DO:
1. ...
2. ...
3. ...

DON'T:
1. ...
2. ...
3. ...

MEDICINE:
Name: ...
Use: ...
`
            });

            return response.text || "No suggestions available";
        } catch (err) {
            console.error("Gemini Error:", err);
            return "Failed to get AI suggestions";
        }
    };
    const handleBuyMedicine = () => {
        if (!result?.medicine) return;

        const query = encodeURIComponent(result.medicine);
        const flipkartURL = `https://www.flipkart.com/search?q=${query}`;

        window.open(flipkartURL, "_blank");
    };


    const handleWatchVideo = () => {
        if (!result?.disease) return;

        const query = encodeURIComponent(
            `${result.disease} plant disease treatment`
        );

        const youtubeURL = `https://www.youtube.com/results?search_query=${query}`;

        window.open(youtubeURL, "_blank");
    };

    const handleAnalyze = async () => {
        if (!file) {
            alert("Please upload image");
            return;
        }

        setLoading(true);
        setResult(null);
        setSolution(null); // reset

        try {
            const formData = new FormData();
            formData.append("file", file);

            const res = await fetch("http://127.0.0.1:8000/predict", {
                method: "POST",
                body: formData,
            });

            const data = await res.json();

            console.log("API 👉", data);

            const cleanName = data.class
                .replace("___", " - ")
                .replace(/_/g, " ");

            setResult({
                disease: cleanName,
                confidence: data.confidence + " %",
                medicine: "Coming soon",
                shop: "Coming soon",
            });

            // 🔥 Gemini call AFTER result
            setLoadingGemini(true);

            getGeminiSolution(cleanName).then((res) => {
                setSolution(res);
                setLoadingGemini(false);
            });

        } catch (err) {
            console.error(err);
        }

        setLoading(false);
    };
    const extractMedicine = (text: string) => {
        const match = text.match(/Name:\s*(.*)/i);
        return match ? match[1] : "Recommended Medicine";
    };
    const getBuyLink = (medicine: string) => {
        const query = encodeURIComponent(medicine);
        return `https://www.flipkart.com/search?q=${query}`;
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-green-50 to-white dark:from-[#0f1f14] dark:to-[#0b1510] px-6 md:px-20 py-20 transition-colors">

            {/* Header */}
            <motion.div
                initial={{ opacity: 0, y: -40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="text-center mb-16"
            >
                <h1 className="text-5xl font-bold text-green-700 dark:text-green-400 flex justify-center items-center gap-4">
                    <Leaf size={40} /> Scan Your Crop
                </h1>
                <p className="mt-4 text-gray-600 dark:text-gray-300 text-lg">
                    Upload a leaf image and let AgroVision AI detect diseases instantly.
                </p>
            </motion.div>

            {/* Upload Section */}
            <motion.div
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6 }}
                className="max-w-3xl mx-auto bg-[#DBFCE7] dark:bg-[#13281b] p-10 rounded-2xl shadow-xl border border-green-200 dark:border-green-800"
            >
                {!image ? (
                    <label className="flex flex-col items-center justify-center border-2 border-dashed border-green-400 rounded-xl p-10 cursor-pointer hover:bg-green-50 dark:hover:bg-green-900 transition">
                        <Upload size={40} className="text-green-600 dark:text-green-400" />
                        <p className="mt-4 text-green-700 dark:text-green-300">
                            Click to Upload Leaf Image
                        </p>
                        <input
                            type="file"
                            accept="image/*"
                            className="hidden"
                            onChange={handleImageUpload}
                        />
                    </label>
                ) : (
                    <div className="text-center">


                        <div className="text-center">
                            <img
                                src={image}
                                alt="Preview"
                                className="mx-auto rounded-xl shadow-lg w-80 h-auto"
                            />

                            <div className="flex justify-center gap-4 mt-6">
                                <button
                                    onClick={handleAnalyze}
                                    className="px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition"
                                >
                                    Analyze Leaf
                                </button>

                                <button
                                    onClick={() => {
                                        setImage(null);
                                        setFile(null);
                                        setResult(null);
                                    }}
                                    className="px-6 py-2 bg-gray-500 text-white rounded-lg hover:bg-gray-600 transition"
                                >
                                    Choose Another
                                </button>
                            </div>
                        </div>



                    </div>
                )}
            </motion.div>

            {/* Loading Spinner */}
            {loading && (
                <motion.div
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="flex justify-center mt-10"
                >
                    <Loader2 className="animate-spin text-green-600" size={40} />
                </motion.div>
            )}

            {/* Result Section */}
            {result && (
                <motion.div
                    initial={{ opacity: 0, y: 40 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6 }}
                    className="max-w-4xl mx-auto mt-16 bg-[#DBFCE7] dark:bg-[#13281b] p-10 rounded-2xl shadow-xl border border-green-200 dark:border-green-800"
                >
                    <h2 className="text-3xl text-green-700 dark:text-green-400 mb-8 text-center font-bold">
                        Scan
                    </h2>

                    <div className="grid md:grid-cols-2 gap-10">
                        <div className="space-y-6">
                            <div className="flex items-center gap-4">
                                <Leaf className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Diseasem:</strong> {result.disease}</p>
                            </div>

                            {/* <div className="flex items-center gap-4">
                                <BarChart3 className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Confidence:</strong> {result.confidence}</p>
                            </div> */}

                            {/* <div className="flex items-center gap-4">
                                <Pill className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Medicine:</strong> {result.medicine}</p>
                            </div> */}


                            <div className="flex items-center gap-4">
                                <Store className="text-green-600" />
                                <p className="text-black dark:text-white "><strong>Nearby Shop:</strong> {result.shop}</p>
                            </div>

                            <div className="flex items-center gap-4">
                                <Pill className="text-green-600" />

                                <div>
                                    <p className="text-black dark:text-white">
                                        <strong>Medicine:</strong>{" "}
                                        {solution ? extractMedicine(solution) : "Loading..."}
                                    </p>

                                    {solution && (
                                        <button
                                            onClick={() =>
                                                window.open(getBuyLink(extractMedicine(solution)), "_blank")
                                            }
                                            className="mt-2 px-4 py-1 bg-green-600 text-white rounded-md text-sm hover:scale-105 transition"
                                        >
                                            Buy Online
                                        </button>
                                    )}
                                </div>
                            </div>
                        </div>

                        <div className="bg-green-50 dark:bg-[#284131b9] p-6 rounded-xl">
                            <p className="font-semibold text-green-700 dark:text-green-300">
                                Recommended Action:
                            </p>
                            <p className="mt-3 text-gray-700 dark:text-gray-100">
                                Apply treatment immediately and monitor crop condition for the
                                next 5-7 days. Avoid overwatering and ensure proper sunlight.
                            </p>
                            <div className="flex justify-between gap-2">



                                <button onClick={handleDownloadPDF} className=" cursor-pointer mt-6 px-6 py-2 bg-green-700 text-white rounded-lg hover:scale-105 transition">
                                    Download Pdf 
                                </button>
                                <button
                                    onClick={handleWatchVideo}
                                    className="mt-6 px-6 py-2 bg-red-600 cursor-pointer text-white rounded-lg hover:scale-105 transition"
                                >
                                    Watch Video
                                </button>
                            </div>
                        </div>


                    </div>

                </motion.div>

            )}


            {
                result &&
                <div className="mx-auto w-fit">

                    <div className="mt-6 inline-block relative rounded-xl p-[2px] overflow-hidden">

                        {/* Rotating gradient border */}
                        <div className="absolute inset-0   rounded-xl   "></div>

                       
                         
                    </div>

                    {loadingGemini && (
                        <div className="flex justify-center mt-4">
                            <Loader2 className="animate-spin text-yellow-400" size={30} />
                            <p className="ml-2 text-yellow-400">Getting AI suggestions...</p>
                        </div>
                    )}

                    {solution && (
                        <div className="mt-6 p-4 bg-green-900/30 rounded-xl ">
                            <h3 className="text-green-700 font-bold mb-2   ">AI Recommendation</h3>
                            <pre className="whitespace-pre-wrap  text-gray-600 dark:text-gray-300 text-lg">
                                {solution}
                            </pre>
                        </div>
                    )}
                </div>
            }
        </div>
    );
}
